#!/bin/bash
#SBATCH --job-name=Q2.1_CutAdpt_160
#SBATCH --mail-type=ALL
#SBATCH --mail-user=thongthum.t@ufl.edu
#SBATCH --output=logs/q2.part01-CutAdapt_20250414.%j.out
#SBATCH --nodes=1
#SBATCH --cpus-per-task=5
#SBATCH --mem-per-cpu=10gb
#SBATCH --account=epi
#SBATCH --qos=epi
#SBATCH --time=120:00:00

pwd; hostname; date

module load qiime2/2024.5

## You need to import the reads first, as they are already demultiplexed:
###  demultiplexedFiles
##for the type want to input fastq only, and in the rawFiles folder need to only have the fastq files in there

qiime tools import \
    --type 'SampleData[SequencesWithQuality]' \
    --input-format CasavaOneEightSingleLanePerSampleDirFmt \
    --input-path /blue/cmavian/thongthum.t/bat16s/out03_cutadapt_160/ \
    --output-path /blue/cmavian/thongthum.t/bat16s/outq2_160nt/step.01c.joined.qza

echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc
#
## or you will get a "invalid display variable" error

qiime demux summarize \
    --i-data step.01c.joined.qza \
    --o-visualization step.01c.joined.qzv

#
#
#
#filtering after joining, deblur already takes read quality into account to make asvs,, but may need to check
## XXX leave 20 for now (sliding window 5), but deblur shouldn't really need that (default=4; window=3)

qiime quality-filter q-score \
    --i-demux step.01c.joined.qza \
    --p-min-quality 4 \
    --p-quality-window 3 \
    --verbose \
    --o-filtered-sequences step.01d.filtered.qza \
    --o-filter-stats step.01d.filtered.stats.qza 
#
#
##need the following to set the default matplotlib backend to Agg in your personal configuration

echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc
#
## or you will get a "invalid display variable" error

# STEP 4: Summarize the filtered sequences
qiime demux summarize \
    --i-data step.01d.filtered.qza \
    --o-visualization step.01d.filtered.qzv

date

###Run for  hours  and used  mb memory
