#!/bin/bash
#SBATCH --job-name Vsearch
#SBATCH --mail-type ALL
#SBATCH --mail-user thongthum.t@ufl.edu
#SBATCH -o ./logs/01.vsearch.%A_%a_2518.out
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=10gb
#SBATCH --account=epi
#SBATCH --qos=epi-b
#SBATCH --time=24:00:00

pwd; hostname; date
module load vsearch/2.30.0

#mkdir -p out01_vsearch

inpDir=/blue/cmavian/thongthum.t/v4-1-2518/v4-1/input/

myFiles=($(<inputFiles_2518.list))
indFile=${myFiles[${SLURM_ARRAY_TASK_ID}]}

#16S V4-1 515F: GTGCCAGCMGCCGCGGTAA
#16S V4-1 806R: GGACTACHVGGGTWTCTAAT

set -e

# Loop through each file in myFiles list
for indFile in "${myFiles[@]}"; do
    echo "Processing: ${indFile}"

    vsearch --fastq_mergepairs \
      ${inpDir}/${indFile}_*_R1_*.fastq.gz \
      --reverse ${inpDir}/${indFile}_*_R2_*.fastq.gz \
      --fastqout ./out01_vsearch/${indFile}.merged.fastq \
      --fastqout_notmerged_fwd ./out01_vsearch/${indFile}.fwd.notmerged.fastq \
      --fastqout_notmerged_rev ./out01_vsearch/${indFile}.rev.notmerged.fastq \
      --fastq_minovlen 50 \
      --fastq_maxdiffs 5 \
      --threads 2

    gzip ./out01_vsearch/${indFile}.merged.fastq

done

date 

# vsearch --fastq_mergepairs \
#  ${inpDir}/${indFile}_*_R1_*.fastq.gz \
#  --reverse ${inpDir}/${indFile}_*_R2_*.fastq.gz \
#  --fastqout ./out01_vsearch/${indFile}.merged.fastq \
#  --fastqout_notmerged_fwd ./out01_vsearch/${indFile}.fwd.notmerged.fastq \
#  --fastqout_notmerged_rev ./out01_vsearch/${indFile}.rev.notmerged.fastq \
#  --threads 2

# gzip ./out01_vsearch/${indFile}.merged.fastq

####note: SBATCH --partition=hpg-default 
